import pip
pip.main(['install', '--user', 'shapelysmooth==0.1.1'])
pip.main(['install', '--user', 'Pillow'])
pip.main(['install', '--user', 'numpy==1.23.0'])
pip.main(['install', '--user', 'customtkinter'])
pip.main(['install', '--user', 'tkscrolledframe'])
pip.main(['install', '--user', 'pandas'])
pip.main(['install', '--user', 'pyautogui'])
pip.main(['install', '--user', 'matplotlib'])
pip.main(['install', '--user', 'mouse'])
pip.main(['install', '--user', 'tkPDFViewer'])
pip.main(['install', '--user', 'networkx'])
